import gridImg from "../assets/grid.svg";
import b4Img from "../assets/b4.svg";
import b5Img from "../assets/b5.svg";
import {
  atcommerce,
  placed,
  techscope,
  atrule,
  qualityShop,
  vero,
  wynshop,
  xora,
  sassApp,
  ninjaTeam,
  pakistaniBrands,
  weather,
  motorway,
  carParking,
  mehndiDesigns,
  petrolPrice,
  mobileShop,
  nopcommerceStore,
  bobiotics,
  placedToday,
  onlineStore,
  clothingStore,
  veroApp,
  atcommerceDesign,
  batteryApp,
  muzamilProfile,
} from "../assets/index";

export const navItems = [
  { name: "Grid", link: "#intro" },
  { name: "Projects", link: "#projects" },
  { name: "Testimonials", link: "#testimonials" },
  { name: "Contact", link: "#contact" },
];

export const gridItems = [
  {
    id: 1,
    title: "I prioritize client collaboration, fostering open communication",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "object-[center_22%]",
    titleClassName: "justify-end",
    img: muzamilProfile,
    spareImg: "",
  },
  {
    id: 2,
    title: "I'm very flexible with time zone communications",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "From complex ideas to dependable digital products",
    description: "I combine thoughtful engineering, clear communication, and product-focused decisions to create software that delivers lasting value.",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "Tech enthusiast with a passion for development.",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: gridImg,
    spareImg: b4Img,
  },
  {
    id: 5,
    title: "Exploring new creative possibilities in software engineering.",
    description: "Passionate about blending architecture, interactivity, and technology for scalable user experiences.",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
    titleClassName: "justify-center md:justify-start lg:justify-top-[50%] top-[5%]",
    img: b5Img,
    spareImg: gridImg,
  },
  {
    id: 6,
    title: "Do you want to start a project together?",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "",
    titleClassName: "justify-center md:max-w-full max-w-60 text-center",
    img: "",
    spareImg: "",
  },
];

export const projects = [
  {
    id: 1,
    title: "3D Solar System Planets to Explore",
    des: "Explore the wonders of our solar system with this captivating 3D simulation of the planets using Three.js.",
    img: "/p1.svg",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/fm.svg"],
    link: "/ui.earth.com",
  },
  {
    id: 2,
    title: "Yoom - Video Conferencing App",
    des: "Simplify your video conferencing experience with Yoom. Seamlessly connect with colleagues and friends.",
    img: "/p2.svg",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/stream.svg", "/c.svg"],
    link: "/ui.yoom.com",
  },
  {
    id: 3,
    title: "AI Image SaaS - Canva Application",
    des: "A REAL Software-as-a-Service app with AI features and a payments and credits system using the latest tech stack.",
    img: "/p3.svg",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/c.svg"],
    link: "/ui.aiimg.com",
  },
  {
    id: 4,
    title: "Animated Apple Iphone 3D Website",
    des: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects..",
    img: "/p4.svg",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
    link: "/ui.apple.com",
  },
];

export const projectsByCategory = {
  webDevelopment: [
    
    {
      id: 1,
      title: "Placed.today - AI-Powered Recruitment Platform",
      description: "AI-powered platform with user/moderator/admin dashboards and role-based management. Built Resume modules, Interview tools, and AI Auto Apply using React, Next.js, and Tailwind CSS. Integrated AI algorithms and REST APIs for automated applications and resume analysis.",
      tags: ["React", "Next.js", "Tailwind CSS", "Redux", "TypeScript", "Node.js", "AI Integration"],
      image: placed,
      source_code_link: "https://www.placed.today/",
    },
    {
      id: 2,
      title: "TechScope - Training & Talent Platform",
      description: "Innovative platform bridging technology education with career opportunities. Offers tech training, talent recruitment, and IT consulting services. Specializes in data solutions, cloud computing, and helping students secure positions at top companies.",
      tags: ["React", "JavaScript", "Node.js", "Cloud Computing", "Data Engineering"],
      image: techscope,
      source_code_link: "https://techscope.org",
    },
    {
      id: 3,
      title: "Quality Shop - DTC Marketplace for Healthy Brands",
      description: "DTC marketplace for healthy brands with scalable Next.js architecture managing 13K+ businesses from 2.5M Shopify stores. Integrated dynamic data visualization, filtering features, and OpenAI API for intelligent classification. Optimized performance with reusable components and efficient API handling.",
      tags: ["Next.js", "React", "Tailwind CSS", "OpenAI API", "PostgreSQL", "GitHub"],
      image: qualityShop,
      source_code_link: "#",
    },
    {
      id: 4,
      title: "AtRule - Remote Developer Hub",
      description: "Expert remote team hiring platform specializing in .NET, MERN stack, mobile development, and AI solutions. Connects businesses with skilled developers across web, backend, mobile, and AI technologies for on-demand team building.",
      tags: [".NET", "React", "Next.js", "Mobile", "AI", "Docker", "AWS"],
      image: atrule,
      source_code_link: "https://atrule.com",
    },
    
    {
      id: 5,
      title: "AtCommerce - Online Ecommerce Store Creation Platform",
      description: "Translated Figma and PSD designs into pixel-perfect, user-friendly UIs with clean, reusable code. Collaborated with cross-functional teams on design, functionality, and performance optimization. Built component libraries and conducted code reviews for maintainability and scalability.",
      tags: ["React", "Next.js", "Tailwind CSS", "GitHub", "Figma", "Responsive Design"],
      image: atcommerce,
      source_code_link: "https://atcommerce.store/",
    },
    
    {
      id: 6,
      title: "WynShop - Customer Order Pickup Dashboard (Instacart)",
      description: "React PWA for retail order management and tracking with real-time updates. Built responsive application flows with Redux Toolkit and Tailwind CSS for scalable performance. Implemented automated testing with Jasmine and maintained code quality with ESLint and SonarQube.",
      tags: ["React PWA", "Redux Toolkit", "Tailwind CSS", "SQL", "Jasmine", "ESLint", "SonarQube"],
      image: wynshop,
      source_code_link: "#",
    },
    {
      id: 7,
      title: "VERO - Event Management & Volunteer Dashboard",
      description: "React event management application with dynamic calendar interface for creating and managing events. Implemented recurring event scheduling and Redux for state management. Built with Bootstrap 5 for responsive UI and intuitive dashboard for real-time tracking.",
      tags: ["React", "Redux", "Bootstrap 5", "JavaScript", "Calendar API", "GitHub"],
      image: vero,
      source_code_link: "https://verodev.atapps.io/",
    },
  ],
  landingPages: [
    {
      id: 1,
      title: "Pakistani Brands Hub",
      description: "E-commerce landing page showcasing Pakistani brands with category filters and product display.",
      tags: ["Next.js", "Stripe", "Database", "E-commerce"],
      image: pakistaniBrands,
      source_code_link: "https://thepakistanibrands.com/",
    },
    {
      id: 2,
      title: "Weather Application",
      description: "Interactive weather app landing page with real-time data, forecasts and location-based services.",
      tags: ["React", "API Integration", "Charts", "Responsive"],
      image: weather,
      source_code_link: "https://moyemoyeweather.com/",
    },
    {
      id: 3,
      title: "Motorway Services",
      description: "Landing page for highway services platform with booking system and service listings.",
      tags: ["Next.js", "Booking System", "Maps", "Tailwind"],
      image: motorway,
      source_code_link: "https://motorwaytoday.pk/",
    },
    {
      id: 4,
      title: "Mehndi Designs Portfolio",
      description: "Creative portfolio landing page showcasing mehndi designs with gallery and booking functionality.",
      tags: ["Portfolio", "Gallery", "Booking", "Design"],
      image: mehndiDesigns,
      source_code_link: "https://mehndipoint.com/",
    },
    {
      id: 5,
      title: "Petrol Price Tracker",
      description: "Real-time fuel price tracking application with historical data and price predictions.",
      tags: ["React", "Charts", "API", "Real-time Data"],
      image: petrolPrice,
      source_code_link: "https://petrolprices.pk/",
    },
    {
      id: 6,
      title: "Car Parking System",
      description: "Smart parking management landing page with real-time parking availability and reservation features.",
      tags: ["React", "Real-time", "Maps", "Payment Integration"],
      image: carParking,
      source_code_link: "https://github.com",
    },
    {
      id: 7,
      title: "Xora - SaaS Platform",
      description: "Modern SaaS landing page with conversion optimization, smooth animations and responsive design.",
      tags: ["React", "Tailwind", "Framer Motion", "Responsive"],
      image: xora,
      source_code_link: "https://famous-hotteok-afcf2e.netlify.app/",
    },
    {
      id: 8,
      title: "Sass App Landing",
      description: "Professional SaaS application landing page with features showcase and call-to-action optimization.",
      tags: ["Next.js", "TypeScript", "Tailwind", "SEO"],
      image: sassApp,
      source_code_link: "https://mellow-genie-ec4db4.netlify.app/",
    },
    {
      id: 9,
      title: "Ninja Team Landing",
      description: "Dynamic team landing page with portfolio showcase and interactive team member profiles.",
      tags: ["React", "Animation", "Portfolio", "Tailwind"],
      image: ninjaTeam,
      source_code_link: "https://fastidious-bonbon-523969.netlify.app/",
    },
  ],
  uiuxDesigns: [
    {
      id: 1,
      title: "Placed Today - Job Portal Design",
      description: "Comprehensive UI/UX design for a modern job portal platform. Features intuitive job search, profile management, and employer dashboard with seamless user experience.",
      tags: ["Figma", "UX Design", "Prototyping", "Job Portal"],
      image: placedToday,
      source_code_link: "https://www.figma.com/design/DmEkGTWb15PP8pJF2vnPsN/Placed--Final?m=auto&t=2Nnumd5kaWc8KR3I-6",
    },
    {
      id: 2,
      title: "Vero App - Web & Mobile Design",
      description: "Comprehensive UI/UX design for Vero App covering both web and mobile platforms. Features consistent design language, intuitive navigation, and responsive layouts optimized for cross-platform user experience.",
      tags: ["Figma", "Web Design", "Mobile Design", "Cross-platform"],
      image: veroApp,
      source_code_link: "https://www.figma.com/design/1zbfJy2gxFsdfuceCRk6uI/Vero-App--1-?node-id=0-1&p=f&t=3wTUHBcOmdwWoSxp-0",
    },
    {
      id: 3,
      title: "Online Store - NopCommerce Design",
      description: "Professional e-commerce UI/UX design for NopCommerce platform. Features product showcase, shopping cart, and checkout flow with modern design aesthetics.",
      tags: ["Figma", "E-commerce Design", "Prototyping", "NopCommerce"],
      image: onlineStore,
      source_code_link: "https://www.figma.com/design/ivCb9XLjYFn48WCg9eN67A/Online-Store--Home-Page-Layout-?node-id=28-3020&p=f&t=kcbdmvFTJGgOQAKr-0",
    },
    {
      id: 4,
      title: "Fashion Clothing Store Design",
      description: "Modern e-commerce clothing store UI/UX design for a multi-purpose mobile app. Features intuitive product browsing, size selection, and seamless checkout experience optimized for fashion retail.",
      tags: ["Figma", "Fashion Design", "Mobile UI", "E-commerce"],
      image: clothingStore,
      source_code_link: "https://www.figma.com/design/C94vLqKVWc9P2uh0aGEqef/Shoppe---eCommerce-Clothing-Fashion-Store-Multi-Purpose-UI-Mobile-App-Design--Community-?node-id=0-1&p=f&t=wF3ybCFuVn9ku5PS-0",
    },
    {
      id: 5,
      title: "AtCommerce - E-commerce Design",
      description: "Comprehensive e-commerce platform UI/UX design featuring product catalog, shopping cart, and checkout flows. Includes admin dashboard design for inventory and order management.",
      tags: ["Figma", "E-commerce", "Dashboard Design", "Web Design"],
      image: atcommerceDesign,
      source_code_link: "https://www.figma.com/design/g5jzCyyGX7QNP5rQFEI0Zx/AtCommerce?node-id=194-107&p=f&t=VfTgUdRDJNicARKR-0",
    },
    {
      id: 6,
      title: "Battery App - Mobile Design",
      description: "Mobile application UI design for battery optimization and power management. Features battery health monitoring, app usage analytics, and power-saving recommendations.",
      tags: ["Figma", "Mobile App", "UI Design", "Productivity"],
      image: batteryApp,
      source_code_link: "https://www.figma.com/design/JN02dXkSrVZUbJnUVH0CBL/Battery-App?node-id=20-282&p=f&t=OroMtC9kvHYE9Cuk-0",
    },
  ],
  ecommerce: [
    {
      id: 1,
      title: "Mobile Shop - NopCommerce",
      description: "Premium mobile e-commerce store built on .NET with NopCommerce platform. Features advanced product filtering, secure checkout, and inventory management.",
      tags: [".NET", "NopCommerce", "E-commerce", "Stripe Payment"],
      image: mobileShop,
      source_code_link: "https://github.com",
    },
    {
      id: 2,
      title: "NopCommerce Store - React",
      description: "Modern React-based e-commerce store powered by NopCommerce API. Implements responsive design, real-time product updates, and seamless shopping experience.",
      tags: ["React", "NopCommerce API", "Redux", "Tailwind CSS"],
      image: nopcommerceStore,
      source_code_link: "https://github.com",
    },
    {
      id: 3,
      title: "Bobiotics - Shopify Store",
      description: "Premium Shopify e-commerce store featuring modern UI, product recommendations, and optimized checkout flow for maximum conversions.",
      tags: ["Shopify", "Liquid", "E-commerce", "Payment Gateway"],
      image: bobiotics,
      source_code_link: "https://github.com",
    },
  ],
};
